#!/usr/bin/env bash

while true; do
    # Accept new local peers
    syncweb devices --local-only --pending --accept

    sleep 5

    # Join pending folders
    syncweb folders --local-only --pending --join

    sleep 10

    # Mark new downloads via wishlists
    paths=$(grep -Fv -f <(blocklist.sh) <(wishlist.sh))
    if [[ -n "$paths" ]]; then
        printf '%s\n' "$paths" | syncweb download --yes
    fi
done
