#!/usr/bin/env bash

while true; do
    # Accept new local peers
    syncweb devices --local-only --pending --accept

    # Join pending folders
    syncweb folders --pending --join

    # Mark new downloads via wishlists
    grep -Fv -f <(blocklist.sh) <(wishlist.sh) | syncweb download --yes

    sleep 20
done
